name: McugCore
version: '${project.version}'
main: com.cleyh.plugin.mcug.Mcug
api-version: 1.19
commands:
  #house-set-apartment:
  #  description: set a hotel!
  #  usage: /house-set apartment [name] [room number]

  house-set-villa:
    description: 登记你的房产（地产）。
    usage: /house-set villa [name] <price(optional)>

  house-del:
    description: 删除你的房产（地产）登记记录。
    usage: /house-del [ID]

